apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: k8s-gateway
version: 0.1.0

dependencies:
- name: k8s-gateway
  version: 2.0.3
  repository:  https://ori-edge.github.io/k8s_gateway/
