---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra
spec:
  generators:
  - git:
      repoURL: https://github.com/mhumeSF/kustomize-helm-example
      revision: HEAD
      directories:
      - path: infra/*/dev
  template:
    metadata:
      name: "{{path[1]}}"
      namespace: argocd
    spec:
      destination:
        name: in-cluster
        namespace: default
      project: default
      source:
        path: '{{path}}'
        repoURL: https://github.com/mhumeSF/kustomize-helm-example
        targetRevision: HEAD
        plugin:
          name: kustomize-helm
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
        syncOptions:
        - allowEmpty=true
