---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra
spec:
  generators:
  - git:
      repoURL: https://github.com/mhumeSF/kustomize-helm-example
      revision: HEAD
      directories:
      - path: infra/networking/*/dev
  template:
    metadata:
      name: "{{path[2]}}"
      namespace: networking
    spec:
      destination:
        name: in-cluster
      project: default
      source:
        path: '{{path}}'
        repoURL: https://github.com/mhumeSF/kustomize-helm-example
        targetRevision: HEAD
        plugin:
          name: kustomize-helm
          parameters:
          - name: namespace
            string: networking
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
        syncOptions:
        - allowEmpty=true
