apiVersion: v2
name: argo-cd
description: ArgoCD Installation for Mememe
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
- name: argo-cd
  version: 5.28.1
  repository: https://argoproj.github.io/argo-helm
- name: argocd-image-updater
  version: 0.9.1
  repository: https://argoproj.github.io/argo-helm
