argo-cd:
  global:
    logging:
      level: debug
  configs:
    cmp:
      create: true
      plugins:
        kustomize-helm:
          allowConcurrency: true
          init:
            command: [sh, -c]
            args:
              - |
                helm dependency build ../base || true
          generate:
            command: [sh, -c]
            args:
              - |
                if [ -f "values.yaml" ]; then
                  helm template $ARGOCD_APP_NAME ../base --include-crds --kube-version $KUBE_VERSION --api-versions $KUBE_API_VERSIONS -f ../base/values.yaml -f values.yaml --namespace $PARAM_NAMESPACE > ../base/all.yaml && kustomize build
                else
                  helm template $ARGOCD_APP_NAME ../base --include-crds --kube-version $KUBE_VERSION --api-versions $KUBE_API_VERSIONS -f ../base/values.yaml --namespace $PARAM_NAMESPACE > ../base/all.yaml && kustomize build
                fi
          parameters:
            static:
            - name: namespace
              title: namespace
              string: default
  repoServer:
    initContainers:
    - name: download-tools
      image: alpine:3.18
      command: [sh, -c]
      args:
      - >-
        wget -O argocd-vault-plugin
        https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v${AVP_VERSION}/argocd-vault-plugin_${AVP_VERSION}_linux_amd64 &&
        chmod +x argocd-vault-plugin &&
        mv argocd-vault-plugin /custom-tools/
      env:
      - name: AVP_VERSION
        value: 1.11.0
      volumeMounts:
      - mountPath: /custom-tools
        name: custom-tools
    extraContainers:
    - name: kustomize-helm
      command: [/var/run/argocd/argocd-cmp-server]
      args:
      - --loglevel
      - debug
      image: quay.io/argoproj/argocd:v2.6.4
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      volumeMounts:
      - mountPath: /var/run/argocd
        name: var-files
      - mountPath: /home/argocd/cmp-server/plugins
        name: plugins
      # Register plugins into sidecar
      - mountPath: /home/argocd/cmp-server/config/plugin.yaml
        subPath: kustomize-helm.yaml
        name: argocd-cmp-cm
      - name: custom-tools
        subPath: argocd-vault-plugin
        mountPath: /usr/local/bin/argocd-vault-plugin
    volumes:
    - name: argocd-cmp-cm
      configMap:
        name: argocd-cmp-cm
    - name: custom-tools
      emptyDir: {}
argocd-image-updater:
  replicaCount: 1
