ingress-nginx:
  controller:
    ingressClass: nginx
    service:
      type: ClusterIP
  admissionWebhooks:
    enabled: false
  hostPort:
    enabled: true
    ports:
      http: 80
      https: 443
